// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGMe_povOCdtDHSljEX2mSlerPPvv78c',
    appId: '1:346757862747:web:42e2eac3e119183f82f67e',
    messagingSenderId: '346757862747',
    projectId: 'app1-7d51a',
    authDomain: 'app1-7d51a.firebaseapp.com',
    storageBucket: 'app1-7d51a.firebasestorage.app',
    measurementId: 'G-RHK85GSF94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6HtACrhTfaF_n-plj68by5Xp0VqnZFo4',
    appId: '1:346757862747:android:c13c1ba0d7f2473b82f67e',
    messagingSenderId: '346757862747',
    projectId: 'app1-7d51a',
    storageBucket: 'app1-7d51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCET1NH7gnHjrh_VjdtUDfPKBbbBWTYNTQ',
    appId: '1:346757862747:ios:e87aec8e21ebca9b82f67e',
    messagingSenderId: '346757862747',
    projectId: 'app1-7d51a',
    storageBucket: 'app1-7d51a.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCET1NH7gnHjrh_VjdtUDfPKBbbBWTYNTQ',
    appId: '1:346757862747:ios:e87aec8e21ebca9b82f67e',
    messagingSenderId: '346757862747',
    projectId: 'app1-7d51a',
    storageBucket: 'app1-7d51a.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGMe_povOCdtDHSljEX2mSlerPPvv78c',
    appId: '1:346757862747:web:5f95dfdb2529a0a982f67e',
    messagingSenderId: '346757862747',
    projectId: 'app1-7d51a',
    authDomain: 'app1-7d51a.firebaseapp.com',
    storageBucket: 'app1-7d51a.firebasestorage.app',
    measurementId: 'G-Q1PYGVS17G',
  );
}
